### ISSUE TITLE
Improve the code coloring

### ISSUE THREAD

**Issue by chasenlehara** [bit-docs/bit-docs-prettify#14]
Right now, the JS code examples are fairly plain; they would be more legible if the coloring was improved.

Maybe related: https://github.com/bit-docs/bit-docs-prettify/issues/12

**Comment by christopherjbaker** [comment]
I made a branch (will open PR once I have access) that adjusts the colors. There are comments in the code that claim to use [tomorrow](https://github.com/chriskempson/tomorrow-theme), but the colors are wrong, so I updated it to use that theme.

Unfortunately, however, the parsing engine is very simplistic and considers a lot of things "plain" and a lot of things "keyword". Here is an example using the new colors. All the gray area is considered "plain". Even though it is in html, the `class` text is a "keyword", but `href` is "plain". With the current engine, no amount of styling can change any of this; we can only change colors of things it already identifies.

![image](https://user-images.githubusercontent.com/980338/35711258-e90e37d8-0770-11e8-9039-cf2a2f0ba1a6.png)
![image](https://user-images.githubusercontent.com/980338/35711342-4b91ca50-0771-11e8-9e26-e49cb99b2213.png)

**Comment by chasenlehara** [comment]
What can we do to fix https://github.com/bit-docs/bit-docs-prettify/issues/12 and improve the coloring? What syntax highlighting libraries are used by other sites?

**Comment by chasenlehara** [comment]
I think Prism is what we use on the Bitovi blog too, so I’d run with that. 😊

**Comment by christopherjbaker** [comment]
Please disregard my above comments and see the updated info on the PR https://github.com/bit-docs/bit-docs-prettify/pull/15#issuecomment-365139564
